GET http://localhost:3001/api/user

###

POST http://localhost:3001/api/user
Content-Type: application/json

 {
  "email" : "email_version_updated8@yahoo.com",
  "password" : "test123456",
  "username": "ryan012297"
}

###

POST http://localhost:3001/api/user/106
Content-Type: application/json

{
  "email": "rest_client_vscode_2000_update@yahoo.com",
  "password": "testupdate"
}

###

DELETE http://localhost:3001/api/user/25

###
POST http://localhost:3001/v1/payment-intents
Content-Type: application/json

{
  "amount": 1099
}